name: Student Data Scraper

on:
  workflow_dispatch:

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    env:
      API_URL: ${{ vars.API_URL }}
      ROLL_NUMBERS: ${{ secrets.ROLL_NUMBERS }}
      ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}

    steps:
    - uses: actions/checkout@v3


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Replace '3.x' with the specific version you need

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the Python script
      run: python fetchStudentDetails-async.py

    - name: Create Archive
      uses: actions/upload-artifact@v4
      with:
        name: student_data
        path: student_data.zip
