name: Student Data Scraper

on:
  workflow_dispatch:

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    env:
      API_URL: ${{ env.API_URL }}
      ROLL_NUMBERS: ${{ secrets.ROLL_NUMBERS }}
      ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install requests logging openpyxl pyminizip

    - name: Run the Python script
      run: python fetchStudentDetails.py

    - name: Create Archive
      uses: actions/upload-artifact@v3
      with:
        name: student_data
        path: student_data.zip
